### ISSUE TITLE
Small warning to every user

### ISSUE THREAD

**Issue by Arcitec** [NickolaiBeloguzov/jsonc-parser#3]
**Edit: SEE NEXT COMMENT IN THIS ISSUE FOR PROPER SOLUTION.**

---

This library is fine for basic parsing, but it's not a proper parser. It's a basic regex.

```python
regex = re.compile(r"(\".*?\"|\'.*?\')|(/\*.*?\*/|//[^\r\n]*$)", re.MULTILINE | re.DOTALL)
newline_replace_regex = re.compile("\n{2,}", re.MULTILINE)
```

This basic regex means that it fails on things like this:

```js
{
/* Commented out
"data": "foo */ bar",
*/
}
```

Because it doesn't understand things like `*/` inside of data fields, or escaped letters like `\*/`.

So don't rely on this package for critical production use. But it's fine for basic little scripts.

Edit: In fact it doesn't even handle escaped quotes inside strings, such as `"hello \"user\""`. So use this library at your own risk.

**Comment by Arcitec** [comment]
## Update: I recommend everyone switch to a JSON5 library instead. JSON5 is JSON with JavaScript features/support. It's the most popular JSON language extension in the world. It has comments, support for trailing commas in objects/arrays, support for single-quoted keys/strings, support for unquoted object keys, etc. And there's proper parser libraries with deep test suites and everything working perfectly.

There are two different, high-quality Python implementations:

- https://github.com/dpranke/pyjson5 (written entirely in Python, it's slow, has its own test suite, project started in 2015 and more "liked"). PyPi Page: https://pypi.org/project/json5/

- **Recommended:** https://github.com/Kijewski/pyjson5 (uses compiled native code via Cython which is much faster, uses the official json5 js test suite instead of its own, project started in 2018). PyPi Page: https://pypi.org/project/pyjson5/

Here's the JSON5 spec: https://json5.org/

**Comment by NickolaiBeloguzov** [comment]
### I ABSOLUTELY SUPPORT COMMENT ABOVE

This project was not originally intended to go public and was created in ~20 minutes to fill a specific need in my other project. For any production-related tasks please use more safer, proper libraries.

Despite this fact this project will still be maintained, just not as often.

Thanks for your attention!
